=== jqk6/squale/Squale/squale-core/src/main/java/com/airfrance/squalecommon/dtd/cpptest-1.0.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT rule
   EMPTY
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST rule
category CDATA #IMPLIED
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST rule
code CDATA #IMPLIED
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST rule
severity CDATA #IMPLIED
>
<!ELEMENT ruleset
   (rule+)
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST ruleset
name CDATA #IMPLIED
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST ruleset
cppTestName CDATA #IMPLIED
>
<!ATTLIST ruleset
version CDATA #IMPLIED
>

=== jqk6/squale/Squale/squale-core/src/main/config/cpptest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ruleset PUBLIC "-//Squale//DTD CppTest Configuration 1.0//EN" "file:../org/squale/squalecommon/dtd/cpptest-1.0.dtd">

<!--TODO la version est 0 en attendant la finalisation de ce fichier -->
<ruleset name="default" version="0" cppTestName="user://MustHaveRules">
	<rule code="CharCompareRight.rule" category="programmingstandard" severity="error" />
	<rule code="NoAbstractClassPointerConvert.rule" category="programmingstandard" severity="error" />
	<rule code="DiffNameLocalAndMemberVars.rule" category="programmingstandard" severity="error" />
	<rule code="IfAssign.rule" category="programmingstandard" severity="error" />
	<rule code="AvoidConvertConstToNonconst.rule" category="programmingstandard" severity="error" />
	<rule code="EqualityFloatRight.rule" category="programmingstandard" severity="error" />
	<rule code="CharCompareLeft.rule" category="programmingstandard" severity="error" />
	<rule code="PublicReturnConst.rule" category="programmingstandard" severity="error" />
	<rule code="EqualityFloatLeft.rule" category="programmingstandard" severity="error" />
	<rule code="VirtualFuncVirtualDestr.rule" category="programmingstandard" severity="error" />
	<rule code="DeleteNonPointer.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-22_ReturnObjectByReference.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-10_CallDeleteIfWriteNew.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-31_LocalVariableAsReturn.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-09_AvoidHidingGlobalNew.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-08_NewAdhereToConvention.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-14_VirtDestrInBaseClass.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-11_CopyConstructorAndAssignmentOperator.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-29_AvoidNonConstAccessToInternalData.rule" category="programmingstandard" severity="error" />
	<rule code="ecpp-15_AssignmentOperatorRetPntThis.rule" category="programmingstandard" severity="error" />
	<rule code="mk-13_AvoidVirtualFunctionCall.rule" category="programmingstandard" severity="error" />
	<rule code="OpEqualThis.rule" category="programmingstandard" severity="error" />
	<rule code="AvoidDirectlyAccessGlobals.rule" category="programmingstandard" severity="error" />
	<rule code="sa-50_BaseClassDestrPubVirtualOrProtNonvirtual.rule" category="programmingstandard" severity="error" />
	<rule code="sa-40_AvoidImplicitConversions.rule" category="programmingstandard" severity="error" />
	<rule code="MemberNotInitializedInConstructor.rule" category="programmingstandard" severity="error" />
</ruleset>
