=== jqk6/squale/Squale/squale-core/src/main/java/com/airfrance/squalecommon/dtd/grid-1.1.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT condition
   (#PCDATA)
>
<!ELEMENT conditionformula
   (level,measures,trigger,conditions)
>
<!ELEMENT conditions
   (condition+)
>
<!ELEMENT criterium
   (practice-ref+)
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST criterium
name CDATA #IMPLIED
>
<!ELEMENT criterium-ref
   EMPTY
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST criterium-ref
name CDATA #IMPLIED
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST criterium-ref
weight CDATA #IMPLIED
>
<!ELEMENT criteriumset
   (criterium+)
>
<!ELEMENT factor
   (criterium-ref+)
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST factor
name CDATA #IMPLIED
>
<!ELEMENT factor-ref
   EMPTY
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST factor-ref
name CDATA #IMPLIED
>
<!ELEMENT factorset
   (factor+)
>
<!ELEMENT formula
   (#PCDATA)
>
<!ELEMENT grid
   (factor-ref+)
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST grid
name CDATA #IMPLIED
>
<!ELEMENT gridset
   (grid)
>
<!ELEMENT helpKey
   (#PCDATA)
>
<!ELEMENT level
   (#PCDATA)
>
<!ELEMENT measure
   (#PCDATA)
>
<!ELEMENT measures
   (measure+)
>
<!ELEMENT practice
   ((weight?,(conditionformula|simpleformula),helpKey?)?)
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST practice
name CDATA #IMPLIED
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST practice
effort CDATA #IMPLIED
>
<!ELEMENT practice-ref
   EMPTY
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST practice-ref
name CDATA #IMPLIED
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST practice-ref
weight CDATA #IMPLIED
>
<!ELEMENT practiceset
   (practice+)
>
<!ELEMENT simpleformula
   (level,measures,trigger,formula)
>
<!ELEMENT squale
   (practiceset,criteriumset,factorset,gridset)
>
<!ELEMENT trigger
   (#PCDATA)
>
<!ELEMENT weight
   (#PCDATA)
>

=== jqk6/squale/Squale/squale-core/src/test/resources/data/grid/grid_compute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE squale PUBLIC "-//Squale//DTD Grid Configuration 1.1//EN" "file:../../../../squaleCommon/src/com/airfrance/squalecommon/dtd/grid-1.1.dtd">

<squale>
	<practiceset>
	    <practice name="practice1">
	    	<weight>lambda x:x</weight>
			<conditionformula>
				<level>class</level>
				<measures>
					<measure>mccabe</measure>
				</measures>
				<trigger>mccabe.wmc >= 8</trigger>
				<conditions>
					<condition>mccabe.maxvg >= 0.5*mccabe.sumvg</condition>
					<condition>mccabe.maxvg >= 0.4*mccabe.sumvg</condition>
					<condition>mccabe.maxvg >= 0.3*mccabe.sumvg</condition>
				</conditions>
			</conditionformula>
	    </practice>

		<practice name="practice2">
	    	<weight>lambda x: 9**-x</weight>
			<simpleformula>
			   <level>project</level>
				<measures>
					<measure>rsm</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger></trigger>
				<formula>3*(2.0/3.0)**(100.0*checkstyle.getTotalErrorNumberForCategory("programmingstandard")/rsm.sloc)</formula>
			</simpleformula>
		</practice>
	    
		<practice name="practice3">
	    	<weight>lambda x:x</weight>
			<conditionformula>
				<level>method</level>
				<measures>
					<measure>mccabe</measure>
				</measures>
				<trigger></trigger>
				<conditions>
					<condition>mccabe.nsloc >= 70</condition>
					<condition>mccabe.nsloc >= 50</condition>
					<condition>mccabe.nsloc >= 40</condition>
				</conditions>
			</conditionformula>
		</practice>

	</practiceset>
	
	<criteriumset>
		<criterium name="criterium1">
			<practice-ref name="practice1" weight="1"/>
			<practice-ref name="practice2" weight="1"/>
			<practice-ref name="practice3" weight="1"/>
		</criterium>

		<criterium name="criterium2">
			<practice-ref name="practice1" weight="1"/>
			<practice-ref name="practice2" weight="1"/>
			<practice-ref name="practice3" weight="1"/>
		</criterium>

	</criteriumset>
	
	<factorset>
		<factor name="factor1"> 
			<criterium-ref name="criterium1" weight="1" />
			<criterium-ref name="criterium2" weight="1" />
		</factor>
		<factor name="factor2"> 
			<criterium-ref name="criterium1" weight="1" />
			<criterium-ref name="criterium2" weight="1" />
		</factor>
	
	</factorset>
	
	<gridset>
		<grid name="grid1">
			<factor-ref name="factor1" />
			<factor-ref name="factor2" />
		</grid>
	</gridset>
</squale>

=== jqk6/squale/Squale/squale-core/src/test/resources/data/grid/grid_rulechecking.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE squale PUBLIC "-//Squale//DTD Grid Configuration 1.1//EN" "file:../../../../squaleCommon/src/org/squale/squalecommon/dtd/grid-1.1.dtd">

<squale>
	<practiceset>
		<practice name="formatingstandard">
	    	<weight>lambda x: x</weight>
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>rsm</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger></trigger>
				<formula>3*(2./3.)**(-(100*checkstyle.getTotalErrorNumberForCategory("formatingstandard")+20*checkstyle.getTotalWarningNumberForCategory("formatingstandard")+5*checkstyle.getTotalInfoNumberForCategory("formatingstandard"))/rsm.sloc)</formula>
			</simpleformula>
		</practice>

		<practice name="namingstandard">
	    	<weight>lambda x: x</weight>
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>rsm</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger></trigger>
				<formula>3*(2./3.)**(-(100*checkstyle.getTotalErrorNumberForCategory("namingstandard")+20*checkstyle.getTotalWarningNumberForCategory("namingstandard")+5*checkstyle.getTotalInfoNumberForCategory("namingstandard"))/rsm.sloc)</formula>
			</simpleformula>		
		</practice>
		<practice name="programmingstandard">
	    	<weight>lambda x: x</weight>
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>rsm</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger></trigger>
				<formula>3*(2./3.)**(-(100*checkstyle.getTotalErrorNumberForCategory("programmingstandard")+20*checkstyle.getTotalWarningNumberForCategory("programmingstandard")+5*checkstyle.getTotalInfoNumberForCategory("programmingstandard"))/rsm.sloc)</formula>
			</simpleformula>		
		</practice>
	</practiceset>

	<criteriumset>		
		<criterium name="homogeneity1">
			<practice-ref name="formatingstandard" weight="1" />
			<practice-ref name="namingstandard" weight="1" />
			<practice-ref name="programmingstandard" weight="1" />
		</criterium>
		<criterium name="homogeneity2">
			<practice-ref name="formatingstandard" weight="1" />
			<practice-ref name="namingstandard" weight="1" />
			<practice-ref name="programmingstandard" weight="1" />
		</criterium>		
	</criteriumset>

	<factorset>
		<factor name="maintainability1">
			<criterium-ref name="homogeneity1" weight="1" />
			<criterium-ref name="homogeneity2" weight="1" />				
		</factor>
		<factor name="maintainability2">
			<criterium-ref name="homogeneity1" weight="1" />
			<criterium-ref name="homogeneity2" weight="1" />				
		</factor>
	</factorset>

	<gridset>
		<grid name="default">
			<factor-ref name="maintainability1" />
			<factor-ref name="maintainability2" />	
		</grid>
	</gridset>
</squale>

=== jqk6/squale/Squale/squale-core/src/main/config/gridcobol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE squale PUBLIC "-//Squale//DTD Grid Configuration 1.1//EN" "file:../org/squale/squalecommon/dtd/grid-1.1.dtd">

<squale>
	<practiceset>
		<!-- pratique non utilisÃ©e pour le moment -->
		<practice name="blob" effort="50">
			<weight>lambda x:9.**-x</weight>
			<conditionformula>
				<level>class</level>
				<measures>
					<measure>mccabe</measure>
				</measures>
				<trigger>mccabe.wmc >= 8 and mccabe.maxvg >= 15</trigger>
				<conditions>
					<condition>mccabe.maxvg >= 0.5*mccabe.sumvg</condition>
					<condition>mccabe.maxvg >= 0.4*mccabe.sumvg</condition>
					<condition>mccabe.maxvg >= 0.3*mccabe.sumvg</condition>
				</conditions>
			</conditionformula>
		</practice>

		<practice name="copypaste" effort="30">
			<weight>lambda x:9**-x</weight>
            <simpleformula>
                <level>project</level>
                <measures>
                    <measure>copypaste</measure>
                    <measure>mccabe</measure>
                </measures>
                <trigger></trigger>
                <formula>3*(2./3.)**(100.*copypaste.duplicateLinesNumber/mccabe.projectsloc)</formula>
            </simpleformula>
		</practice>

        <practice name="documentation" effort="10">
			<weight>lambda x:9.**-x</weight>
            <simpleformula>
                <level>method</level>
                <measures>
                    <measure>mccabe</measure>
                </measures>
                <trigger>(mccabe.vg > 5 or mccabe.nsloc > 30) and mccabe.nsloc != 0</trigger>
                <formula> (mccabe.ncloc)*9./(mccabe.ncloc+mccabe.nsloc) / (1. - 10**(-mccabe.vg /15.))</formula>
            </simpleformula>
            <helpKey>documentationKey</helpKey>
        </practice>

		<practice name="modulesize" effort="20">
			<weight>lambda x:30.**-x</weight>
			<simpleformula>
				<level>method</level>
				<measures>
					<measure>mccabe</measure>
				</measures>
				<trigger></trigger>
				<formula>exp((70-mccabe.nsloc)/30.)</formula>
				<!--
					<condition>mccabe.nsloc >= 70</condition>
					<condition>mccabe.nsloc >= 50</condition>
					<condition>mccabe.nsloc >= 40</condition>
				-->
			</simpleformula>
		</practice>

		<practice name="spaghetticode" effort="30">
			<weight>lambda x:30.**-x</weight>
			<simpleformula>
				<level>method</level>
				<measures>
					<measure>mccabe</measure>
				</measures>
				<trigger></trigger>
				<formula>exp((6-mccabe.evg)/4.)</formula>
				<!--
					<condition>mccabe.evg >= 7</condition>
					<condition>mccabe.evg >= 6</condition>
					<condition>mccabe.evg >= 3</condition>
				-->
			</simpleformula>
		</practice>
		
		<practice name="deadcode" effort="5">
			<weight>lambda x:9.**-x</weight>
			<conditionformula>
				<level>method</level>
				<measures>
					<measure>mccabe</measure>
				</measures>
				<trigger></trigger>
				<conditions>
					<condition>mccabe.deadCode</condition>
					<condition>0</condition>
					<condition>0</condition>
				</conditions>
			</conditionformula>
		</practice>
			
	</practiceset>

	<criteriumset>
		<criterium name="comprehension">
			<practice-ref name="documentation" weight="1" />
			<practice-ref name="deadcode" weight="1" />
		</criterium>

		<criterium name="modularity">
			<practice-ref name="copypaste" weight="1" />
		</criterium>

		<criterium name="simplicity">
			<practice-ref name="modulesize" weight="1" />
			<practice-ref name="spaghetticode" weight="1" />
		</criterium>
	</criteriumset>

	<factorset>
		<factor name="evolutionarity">
			<criterium-ref name="comprehension" weight="1" />
			<criterium-ref name="modularity" weight="1" />
		</factor>

		<factor name="maintainability">
			<criterium-ref name="comprehension" weight="1" />
			<criterium-ref name="simplicity" weight="1" />
		</factor>

		<factor name="reliability">
			<criterium-ref name="simplicity" weight="1" />
		</factor>

		<factor name="reusecapacity">
			<criterium-ref name="comprehension" weight="1" />
		</factor>
	</factorset>

	<gridset>
		<grid name="cobol">
			<factor-ref name="evolutionarity" />
			<factor-ref name="maintainability" />
			<factor-ref name="reliability" />
			<factor-ref name="reusecapacity" />
		</grid>
	</gridset>
</squale>
