=== jqk6/squale/Squale/squale-core/src/main/java/com/airfrance/squalecommon/dtd/grid-1.2.dtd
<?xml version='1.0' encoding="UTF-8"?>


<!ELEMENT squale (practiceset,criteriumset,factorset,gridset)>

	<!ELEMENT practiceset (practice+)>
		<!ELEMENT practice ((weight?,(timeLimitation|conditionformula|simpleformula),helpKey?)?)>
			<!ATTLIST practice name CDATA #IMPLIED>
			<!ATTLIST practice effort CDATA #IMPLIED>
			<!ELEMENT weight (#PCDATA)>
			<!ELEMENT conditionformula (level,measures,trigger,conditions)>
				<!ELEMENT level (#PCDATA)>
				<!ELEMENT measures (measure+)>
					<!ELEMENT measure (#PCDATA)>
				<!ELEMENT trigger (#PCDATA)>
				<!ELEMENT conditions (condition+)>
					<!ELEMENT condition (#PCDATA)>
			<!ELEMENT simpleformula (level,measures,trigger,formula)>
				<!ELEMENT formula (#PCDATA)>
			<!ELEMENT timeLimitation (#PCDATA)>
				<!ATTLIST timeLimitation unit (DAY | MONTH | YEAR) #REQUIRED>
			<!ELEMENT helpKey (#PCDATA)>
	
	
	<!ELEMENT criteriumset (criterium+)>
		<!ATTLIST criterium name CDATA #IMPLIED>
		<!ELEMENT criterium (practice-ref+)>
			<!ELEMENT practice-ref EMPTY>
				<!ATTLIST practice-ref name CDATA #IMPLIED>
				<!ATTLIST practice-ref weight CDATA #IMPLIED>
	
		
	<!ELEMENT factorset (factor+)>
		<!ELEMENT factor (criterium-ref+)>
			<!ATTLIST factor name CDATA #IMPLIED>
			<!ELEMENT criterium-ref EMPTY>
				<!ATTLIST criterium-ref name CDATA #IMPLIED>
				<!ATTLIST criterium-ref weight CDATA #IMPLIED>
	
	
	<!ELEMENT gridset (grid)>
		<!ELEMENT grid (factor-ref+)>
			<!ATTLIST grid name CDATA #IMPLIED>
			<!ELEMENT factor-ref EMPTY>
				<!ATTLIST factor-ref name CDATA #IMPLIED>

=== jqk6/squale/Squale/squale-config/quality-grids/Squale-Java-EE-Grid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE squale PUBLIC "-//Squale//DTD Grid Configuration 1.2//EN" "file:../com/airfrance/squalecommon/dtd/grid-1.2.dtd">

<squale>
	<practiceset>
		<practice name="acceptancetestcodecoverage"></practice>

		<practice name="acceptancetestscenario"></practice>

		<practice name="afferentcoupling" effort="150">
			<weight>lambda x:30.**-x</weight>
			<simpleformula>
				<level>class</level>
				<measures>
					<measure>ckjm</measure>
				</measures>
				<trigger></trigger>
				<formula>exp((30.-ckjm.ca)/10.)</formula>
			</simpleformula>
		</practice>
		
		<practice name="antipatternpredetection"></practice>

		<practice name="aqplan"></practice>

		<practice name="automaticacceptancetest"></practice>

		<practice name="classspecialization"></practice>
		
		<practice name="codeorganisation"></practice>

		<practice name="copypaste" effort="30">
            <simpleformula>
                <level>project</level>
                <measures>
                    <measure>copypaste</measure>
                    <measure>javancss</measure>
                </measures>
                <trigger></trigger>
                <formula>3*(2./3.)**(100.*copypaste.duplicateLinesNumber/javancss.ncss)</formula>
            </simpleformula>
		</practice>

		<practice name="dependencycycle" effort="10">
			<weight>lambda x:3**-x</weight>
			<conditionformula>
				<level>package</level>
				<measures>
					<measure>jdepend</measure>
				</measures>
				<trigger></trigger>
				<conditions>
					<condition>jdepend.cycle</condition>
					<condition>0</condition>
					<condition>0</condition>
				</conditions>
			</conditionformula>
		</practice>

        <practice name="documentation"></practice>
		
		<practice name="documentationquality"></practice>

		<practice name="documentationstandard" effort="6">
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>javancss</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger>checkstyle.hasRule("documentationstandard")</trigger>
				<formula>3*(2./3.)**((500.*checkstyle.getTotalErrorNumberForCategory("documentationstandard")+30.*checkstyle.getTotalWarningNumberForCategory("documentationstandard")+5.*checkstyle.getTotalInfoNumberForCategory("documentationstandard"))/javancss.ncss)</formula>
			</simpleformula>
		</practice>

		<practice name="efferentcoupling" effort="100">
			<weight>lambda x:9.**-x</weight>
			<simpleformula>
				<level>class</level>
				<measures>
					<measure>ckjm</measure>
				</measures>
				<trigger></trigger>
				<formula>exp((10-ckjm.cbo)/3.)</formula>
			</simpleformula>
		</practice>

		<practice name="ergonomynorms"></practice>
		
		<practice name="exceptionhandling"></practice>

		<practice name="formatingstandard" effort="1">
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>javancss</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger>checkstyle.hasRule("formatingstandard")</trigger>
				<formula>3*(2./3.)**((100.*(checkstyle.getTotalErrorNumberForCategory("formatingstandard"))+20.*(checkstyle.getTotalWarningNumberForCategory("formatingstandard"))+5.*(checkstyle.getTotalInfoNumberForCategory("formatingstandard")))/javancss.ncss)</formula>
			</simpleformula>
		</practice>
		
		<practice name="functionalsecurityaspects"></practice>
		
		<practice name="implementationmatchmodel"></practice>

		<practice name="inheritancedepth" effort="20">
			<weight>lambda x:9.**-x</weight>
			<conditionformula>
				<level>class</level>
				<measures>
					<measure>ckjm</measure>
				</measures>
				<trigger></trigger>
				<conditions>
					<condition>ckjm.dit > 5</condition>
					<condition>ckjm.dit > 4</condition>
					<condition>ckjm.dit > 3</condition>
				</conditions>
			</conditionformula>
		</practice>
		
		<practice name="functionallimitstesting"></practice>

		<practice name="functionalspecification"></practice>
		
		<practice name="implementationmatchspecification"></practice>
		
		<practice name="integrationtestcoverage"></practice>

        <practice name="jspdocumentation"></practice>
        
		<practice name="jspsize" effort="15"></practice>
		
		<practice name="jspstandard" effort="15">
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>jsppmd</measure>
				</measures>
				<trigger>jsppmd.hasRule("jspstandard")</trigger>
				<formula>3*(2./3.)**(100*(jsppmd.getTotalErrorNumberForCategory("jspstandard"))+20*(jsppmd.getTotalWarningNumberForCategory("jspstandard"))+5*(jsppmd.getTotalInfoNumberForCategory("jspstandard")))</formula>
			</simpleformula>		
		</practice>
		
		<practice name="jspspaghetticode" effort="20"></practice>
		
		<practice name="layeredarchitecture"></practice>

		<practice name="layerrespect" effort="40">
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>javancss</measure>
					<measure>macker</measure>
				</measures>
				<trigger></trigger>
				<formula>3*(2./3.)**((500.*macker.getTotalErrorNumber()+30.*macker.getTotalWarningNumber()+5.*macker.getTotalInfoNumber())/javancss.classes)</formula>
			</simpleformula>
		</practice>

		<practice name="lackofcohesioninmethod" effort="20">
			<weight>lambda x:9.**-x</weight>
            <conditionformula>
                <level>class</level>
                <measures>
                    <measure>ckjm</measure>
                </measures>
                <trigger></trigger>
                <conditions>
                    <condition>ckjm.lcom >= 100</condition>
                    <condition>ckjm.lcom > 50</condition>
                    <condition>ckjm.lcom > 0</condition>
                </conditions>
            </conditionformula>
        </practice>
		
		<practice name="loadtesting"></practice>
		
		<practice name="mechanismchoices"></practice>

		<practice name="methodsize" effort="20">
			<weight>lambda x:9.**-x</weight>
			<simpleformula>
				<level>method</level>
				<measures>
					<measure>javancss</measure>
				</measures>
				<trigger></trigger>
				<formula>exp((70-javancss.ncss)/30.)</formula>
			</simpleformula>
		</practice>

		<practice name="modelingdiagrams"></practice>

		<practice name="modelsreasoning"></practice>

		<practice name="namingstandard" effort="4">
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>javancss</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger>checkstyle.hasRule("namingstandard")</trigger>
				<formula>3*(2./3.)**((200.*(checkstyle.getTotalErrorNumberForCategory("namingstandard"))+25.*(checkstyle.getTotalWarningNumberForCategory("namingstandard"))+5.*(checkstyle.getTotalInfoNumberForCategory("namingstandard")))/javancss.ncss)</formula>
			</simpleformula>		
		</practice>

		<practice name="numberofmethods" effort="20">
			<weight>lambda x:30.**-x</weight>
			<simpleformula>
				<level>class</level>
				<measures>
					<measure>javancss</measure>
				</measures>
				<trigger></trigger>
				<formula>(javancss.sumVg>=80) and exp((30-javancss.methods)/15.) or (javancss.sumVg>=50 and javancss.methods>=15) and (2+(20-javancss.methods)/30.) or (javancss.sumVg>=30) and (3+(15-javancss.methods)/15.) or 3.</formula>
			</simpleformula>		
		</practice>
		
		<practice name="packagingcompliance"></practice>
		
		<practice name="packagenamingrespectlayers"></practice>
		
		<practice name="portability"></practice>

		<practice name="programmingstandard" effort="15">
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>javancss</measure>
					<measure>checkstyle</measure>
					<measure>javapmd</measure>
				</measures>
				<trigger>checkstyle.hasRule("programmingstandard") or javapmd.hasRule("programmingstandard")</trigger>
				<formula>3*(2./3.)**((200.*(checkstyle.getTotalErrorNumberForCategory("programmingstandard")+javapmd.getTotalErrorNumberForCategory("programmingstandard"))+25.*(checkstyle.getTotalWarningNumberForCategory("programmingstandard")+javapmd.getTotalWarningNumberForCategory("programmingstandard"))+5.*(checkstyle.getTotalInfoNumberForCategory("programmingstandard")+javapmd.getTotalInfoNumberForCategory("programmingstandard")))/javancss.ncss)</formula>
			</simpleformula>		
		</practice>

		<practice name="riskanalysis"></practice>
		
		<practice name="robustnesstesting"></practice>
		
		<practice name="securityconventions" effort="15">
			<simpleformula>
				<level>project</level>
				<measures>
					<measure>javancss</measure>
					<measure>checkstyle</measure>
				</measures>
				<trigger>checkstyle.hasRule("securitystandard")</trigger>
				<formula>3*(2./3.)**((500.*checkstyle.getTotalErrorNumberForCategory("securitystandard")+30.*checkstyle.getTotalWarningNumberForCategory("securitystandard")+5.*checkstyle.getTotalInfoNumberForCategory("securitystandard"))/javancss.ncss)</formula>
			</simpleformula>
		</practice>
		
		<practice name="securitytechnicaldesignfile"></practice>

		<practice name="spaghetticode" effort="30">
			<weight>lambda x:9.**-x</weight>
			<simpleformula>
				<level>method</level>
				<measures>
					<measure>javancss</measure>
				</measures>
				<trigger></trigger>
				<formula>exp((6-javancss.ccn)/4.)</formula>
			</simpleformula>
		</practice>

		<practice name="stabilityabstractnesslevel" effort="200">
			<weight>lambda x:3.**-x</weight>
			<simpleformula>
				<level>package</level>
				<measures>
					<measure>jdepend</measure>
				</measures>
				<trigger></trigger>
				<formula>3+2*(25-jdepend.distance)/25.</formula>
			</simpleformula>
		</practice>

		<practice name="swissarmyknife" effort="35">
			<weight>lambda x:30.**-x</weight>
			<conditionformula>
				<level>class</level>
				<measures>
