=== jqk6/squale/Squale/squale-core/src/main/java/org/squale/squalecommon/dtd/message-1.0.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT message
   (#PCDATA)
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST message
key CDATA #REQUIRED
>
<!--
   <annotation>
      <appinfo source='com.ibm.DDbEv2.Models.AbstractXModel.POSSIBLE'>
         <restriction base='string'/>
      </appinfo>
   </annotation>
-->

<!ATTLIST message
lang CDATA #REQUIRED
>
<!ELEMENT messages
   (message+)
>

=== jqk6/squale/Squale/squale-core/src/main/config/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages PUBLIC "-//Squale//DTD Message Configuration 1.0//EN" "file:../com/airfrance/squalecommon/dtd/message-1.0.dtd">

<messages>
	<!--  Messages de la grille qualité  -->
	<!--  Facteurs  -->
	<message lang="fr" key="rule.reliability">Fiabilité</message>
	<message lang="en" key="rule.reliability">Reliability</message>
	<message lang="fr" key="rule.reusecapacity">
		Réutilisabilité
	</message>
	<message lang="en" key="rule.reusecapacity">Reusecapacity</message>
	<message lang="fr" key="rule.evolutionarity">Evolutivité</message>
	<message lang="en" key="rule.evolutionarity">
		Evolutionarity
	</message>
	<message lang="fr" key="rule.maintainability">
		Maintenabilité
	</message>
	<message lang="en" key="rule.maintainability">
		Maintainability
	</message>
	<message lang="fr" key="rule.architecture">Architecture</message>
	<message lang="en" key="rule.architecture">Architecture</message>
	<message lang="fr" key="rule.conformity">Conformité</message>
	<message lang="en" key="rule.conformity">Conformity</message>
	<!--  Critères  -->
	<message lang="fr" key="rule.modularity">Modularité</message>
	<message lang="en" key="rule.modularity">Modularity</message>
	<message lang="fr" key="rule.integrationcapacity">
		Dépendance interne
	</message>
	<message lang="en" key="rule.integrationcapacity">
		Integration capacity
	</message>
	<message lang="fr" key="rule.simplicity">Simplicité</message>
	<message lang="en" key="rule.simplicity">Simplicity</message>
	<message lang="fr" key="rule.comprehension">Compréhension</message>
	<message lang="en" key="rule.comprehension">Comprehension</message>
	<message lang="fr" key="rule.homogeneity">Homogénéité</message>
	<message lang="en" key="rule.homogeneity">Homogeneity</message>
	<message lang="fr" key="rule.architecturerespect">
		Respect de l'architecture
	</message>
	<message lang="en" key="rule.architecturerespect">
		Architecture respect
	</message>
	<message lang="fr" key="rule.architecturerelevance">
		Pertinence de l'architecture
	</message>
	<message lang="en" key="rule.architecturerelevance">
		Architecture relevance
	</message>
	<message lang="fr" key="rule.exploitability">
		Exploitabilité
	</message>
	<message lang="en" key="rule.exploitability">
		Exploitability
	</message>
	<message lang="fr" key="rule.modeling">Modélisation</message>
	<message lang="en" key="rule.modeling">Modeling</message>
	<message lang="fr" key="rule.performances">Performances</message>
	<message lang="en" key="rule.performances">Performances</message>
	<message lang="fr" key="rule.stability">Stabilité</message>
	<message lang="en" key="rule.stability">Stability</message>
	<message lang="fr" key="rule.testquality">Tests techniques</message>
	<message lang="en" key="rule.testquality">Test quality</message>
	<message lang="fr" key="rule.acceptancetest">
		Recette fonctionnelle
	</message>
	<message lang="en" key="rule.acceptancetest">
		Acceptance test
	</message>
	<message lang="fr" key="rule.taskaptitude">
		Aptitude à la tâche
	</message>
	<message lang="en" key="rule.taskaptitude">Task aptitude</message>
	<!--  Pratiques  -->
	<message lang="fr" key="rule.blob">Pieuvre</message>
	<message lang="en" key="rule.blob">Blob</message>
	<message lang="fr" key="rule.inheritancedepth">
		Profondeur d'héritage
	</message>
	<message lang="en" key="rule.inheritancedepth">
		Inheritance depth
	</message>
	<message lang="fr" key="rule.afferentcoupling">
		Couplage afferent
	</message>
	<message lang="en" key="rule.afferentcoupling">
		Afferent coupling
	</message>
	<message lang="fr" key="rule.numberofmethods">
		Nombre de méthodes
	</message>
	<message lang="en" key="rule.numberofmethods">
		Number of methods
	</message>
	<message lang="fr" key="rule.swissarmyknife">
		Couteau suisse
	</message>
	<message lang="en" key="rule.swissarmyknife">
		Swiss army knife
	</message>
	<message lang="fr" key="rule.efferentcoupling">
		Couplage efferent
	</message>
	<message lang="en" key="rule.efferentcoupling">
		Efferent coupling
	</message>
	<message lang="fr" key="rule.documentation">Documentation</message>
	<message lang="en" key="rule.documentation">Documentation</message>
	<message lang="fr" key="rule.jspdocumentation">
		Documentation des scriptlets JSP
	</message>
	<message lang="en" key="rule.jspdocumentation">
		JSP's scriptlets documentation
	</message>
	<message lang="fr" key="rule.methodsize">
		Taille de la méthode
	</message>
	<message lang="en" key="rule.modulesize">Module size</message>
	<message lang="fr" key="rule.modulesize">
		Taille du module
	</message>
	<message lang="en" key="rule.methodsize">Method size</message>
	<message lang="fr" key="rule.jspsize">Taille de la JSP</message>
	<message lang="en" key="rule.jspsize">JSP size</message>
	<message lang="fr" key="rule.spaghetticode">Code Spaghetti</message>
	<message lang="en" key="rule.spaghetticode">Spaghetti code</message>
	<message lang="fr" key="rule.jspspaghetticode">
		Code Spaghetti des JSP
	</message>
	<message lang="en" key="rule.jspspaghetticode">
		JSP spaghetti code
	</message>
	<message lang="fr" key="rule.jspcomplexity">
		Complexité des JSP
	</message>
	<message lang="en" key="rule.jspcomplexity">JSP complexity</message>
	<message lang="fr" key="rule.architecturefile">
		Dossier d'architecture
	</message>
	<message lang="en" key="rule.architecturefile">
		Architecture file
	</message>
	<message lang="fr" key="rule.layering">
		Découpage en couches
	</message>
	<message lang="en" key="rule.layering">Layering</message>
	<message lang="fr" key="rule.benchmarksprocedure">
		Existence et résultats de la procédure de tests de performance
	</message>
	<message lang="en" key="rule.benchmarksprocedure">
		Existence et results of the benchmark procedure
	</message>
	<message lang="fr" key="rule.copypaste">Copier-coller</message>
	<message lang="en" key="rule.copypaste">Copy paste</message>
	<message lang="fr" key="rule.deploymentpackaging">
		"Normes et standards" : packaging de déploiement
	</message>
	<message lang="en" key="rule.deploymentpackaging">
		Deployment packaging standard
	</message>
	<message lang="fr" key="rule.documentationquality">
		Existence et qualité de la documentation
	</message>
	<message lang="en" key="rule.documentationquality">
		Documentation quality
	</message>
	<message lang="fr" key="rule.documentationstandard">
		"Normes et standard" : documentation
	</message>
	<message lang="en" key="rule.documentationstandard">
		Documentation standard
	</message>
	<message lang="fr" key="rule.formatingstandard">
		"Normes et standards" : mise en forme
	</message>
	<message lang="en" key="rule.formatingstandard">
		Formating standard
	</message>
	<message lang="fr" key="rule.integrationtestsprocedure">
		Existence et résultats de la procédure de tests d'intégration
	</message>
	<message lang="en" key="rule.integrationtestsprocedure">
		Integration tests procedure
	</message>
	<message lang="fr" key="rule.loadtestsprocedure">
		Existence et résultats de la procédure de tests de charge
	</message>
	<message lang="en" key="rule.loadtestsprocedure">
		Load tests procedure
	</message>
	<message lang="fr" key="rule.memoryleaktest">
		Memory leak test
	</message>
	<message lang="en" key="rule.memoryleaktest">
		Tests de fuite mémoire
	</message>
	<message lang="fr" key="rule.modelingdiagrams">
		Diagrammes de modélisation
	</message>
	<message lang="en" key="rule.modelingdiagrams">
		Modeling diagrams
	</message>
	<message lang="fr" key="rule.modelingimplementationconformity">
		Conformité entre modélisation et implémentation
	</message>
	<message lang="en" key="rule.modelingimplementationconformity">
		Modeling and implementation conformity
	</message>
	<message lang="fr" key="rule.modelsreasoning">
		Raisonnement par les modèles
	</message>
	<message lang="en" key="rule.modelsreasoning">
		Models reasoning
	</message>
	<message lang="fr" key="rule.namingstandard">
		"Normes et standards" : nommage
	</message>
	<message lang="en" key="rule.namingstandard">
		Naming standard
	</message>
	<message lang="fr" key="rule.portabilitystandard">
		"Normes et standards" : portabilité
	</message>
	<message lang="en" key="rule.portabilitystandard">
		Portability standard
	</message>
	<message lang="fr" key="rule.programmingstandard">
		"Normes et standards" : programmation
	</message>
	<message lang="en" key="rule.programmingstandard">
		Programming standard
	</message>
	<message lang="fr" key="rule.restartingprocedure">
		Existence et qualité d'une procédure de redémarrage
	</message>
	<message lang="en" key="rule.restartingprocedure">
		Restarting procedure
	</message>
	<message lang="fr" key="rule.robustnesstests">
		Existence d'un processus de tests de robustesse
	</message>
	<message lang="en" key="rule.robustnesstests">
		Robustness tests
	</message>
	<message lang="fr" key="rule.tracingstandard">
		"Normes et standards" : traçage
	</message>
	<message lang="en" key="rule.tracingstandard">
		Tracing standard
	</message>
	<message lang="fr" key="rule.unittestsprocedure">
		Existence et résultats de la procédure de tests unitaires
	</message>
	<message lang="en" key="rule.unittestsprocedure">
		Unit tests procedure
	</message>
	<message lang="fr" key="rule.acceptancetestcodecoverage">
		Taux de couverture de la recette fonctionnelle
	</message>
	<message lang="en" key="rule.acceptancetestcodecoverage">
		Acceptance test code coverage
	</message>
	<message lang="fr" key="rule.acceptancetestscenario">
		Existence de scénarios de recette fonctionnelle
	</message>
	<message lang="en" key="rule.acceptancetestscenario">
		Acceptance test scenario
	</message>
	<message lang="fr" key="rule.aqplan">
