=== jqk6/squale/Squale/squalix/src/main/resources/config/compiling-config.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT configuration (java,cpp)>

<!-- configuration du tag java -->
<!ELEMENT java (general, parsing)>
    <!ELEMENT general (separators, default_jdk_version, dest_dir, required_memory)>
        <!ELEMENT separators (separator+)>
            <!ELEMENT separator (#PCDATA)>
                <!ATTLIST separator name CDATA #REQUIRED value CDATA #REQUIRED>
        <!ELEMENT default_jdk_version (#PCDATA)>
        <!ELEMENT dest_dir (#PCDATA)>
        <!ELEMENT required_memory (#PCDATA)>
    <!ELEMENT parsing (wsad)>
        <!ELEMENT wsad (filename, keys, values)>
            <!ELEMENT filename (#PCDATA)>
            <!ELEMENT keys (key+)>
                <!ELEMENT key (#PCDATA)>
                    <!ATTLIST key name CDATA #REQUIRED value CDATA #REQUIRED>
            <!ELEMENT values (value+)>
                <!ELEMENT value (#PCDATA)>
                    <!ATTLIST value name CDATA #REQUIRED value CDATA #REQUIRED>     


<!-- configuration du tag cpp -->
<!ELEMENT cpp (script)>
    <!ELEMENT script (vars)>
        <!ELEMENT vars (var+)>
            <!ELEMENT var (#PCDATA)>
                <!ATTLIST var name CDATA #REQUIRED value CDATA #REQUIRED>

=== jqk6/squale/Squale/squalix/src/test/java/config/compiling-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- <!DOCTYPE configuration SYSTEM "compiling-config.dtd"> -->
<configuration>
    <java>
        <general>
            <separators>
                <separator name="classpath" value=";" />
            </separators>
            <bootclasspaths>
            	<bootclasspath version="1.4" path="C:/j2sdk1.4.2_12/jre/lib/rt.jar" />
            </bootclasspaths>
            <default_jdk_version>1_4</default_jdk_version>
            <dest_dir>bin/</dest_dir>
            <required_memory>1024m</required_memory>
            <eclipse_bundle_path>./data/eclipse_bundle</eclipse_bundle_path>
            <exported_libs_path>./data/exported_libs</exported_libs_path>
        </general>
    
        <parsing>
            <wsad>
                <filename>.classpath</filename>
                <keys>
                    <key name="classpath" value="classpath" />
                    <key name="classpathentry" value="classpathentry" />
                    <key name="kind" value="kind" />
                    <key name="path" value="path" />
                    <key name="exported" value="exported" />
                </keys>
                <values>
                    <value name="src" value="src" />
                    <value name="lib" value="lib" />
                    <value name="var" value="var" />
                    <value name="con" value="con" />
                </values>
            </wsad>
        </parsing>
    
    </java>
    
    <cpp>
        <script>
            <scriptname>data/cpp_squale_compilation.sh</scriptname>
            <vars>
                <var name="USE_MCCABE" value="1" />
            </vars>
        </script>    
    </cpp>
</configuration>
