=== jqk6/squale/Squale/squalix/src/main/resources/config/eclipsecompiling-config.dtd
<?xml version='1.0' encoding="utf-8"?>
<!ELEMENT options
   (option+)
>
<!ELEMENT workspace
   (#PCDATA)
>
<!ELEMENT command
   (executable,options)
>
<!ELEMENT squaleEclipseHome
   (#PCDATA)
>
<!ELEMENT eclipseHome
   (#PCDATA)
>
<!ELEMENT rightScript
   (#PCDATA)
>
<!ELEMENT copyScript
   (#PCDATA)
>
<!ELEMENT configuration
   (workspace, command, squaleEclipseHome, eclipseHome, rightScript, copyScript)
>
<!ELEMENT executable
   (#PCDATA)
>
<!ELEMENT option
   (#PCDATA)
>

=== jqk6/squale/Squale/squalix/src/test/java/config/eclipsecompiling-config.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE configuration PUBLIC "-//EclipseCompiling Configuration DTD //EN" "file:../../../squalix/src/config/eclipsecompiling-config.dtd">

<configuration>
	<!--  ENV-ECLIPSE-WORKSPACE -->
	<workspace>D:</workspace>
	<command>
		<executable>java</executable>
		<options>
			<!--  ENV-ECLIPSE-JAR -->
			<option>-jar [squale_eclipse_home]/org.eclipse.equinox.launcher_1.0.0.v20070606.jar</option>
			<option>-data [workspace]</option>
			<option>-application org.squale.squale.builder.eclipse32.workspaceId1</option>
			<option>-dialect [dialect]</option>
			<option>-sunLibs [sun_libs]</option>
			<option>-projects [projects_list]</option>
			<option>-outputDir [outputDir]</option>
			<option>-varLibs [var_libs]</option>
			<option>-excluded [excluded_patterns]</option>
		</options>
	</command>
	<!-- ENV-JCOMPILING-ECLIPSE-BUNDLE -->
	<squaleEclipseHome>C:/eclipse_3_2_1/plugins</squaleEclipseHome>
	<eclipseHome>plugins</eclipseHome>
	<!-- ENV-ECLIPSE-RIGHT_SCRIPT -->
	<rightScript>script1.sh</rightScript>
	<!-- ENV-ECLIPSE-COPY-SCRIPT -->
	<copyScript>script2.sh</copyScript>
</configuration>

=== jqk6/squale/Squale/squalix/src/assembly/resources/config/eclipsecompiling-config.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE configuration PUBLIC "-//EclipseCompiling Configuration DTD //EN" "file:../src/config/eclipsecompiling-config.dtd">

<configuration>
	<!--  ENV-ECLIPSE-WORKSPACE -->
	<workspace>/app/SQUALE/dev/data/jcompiling/workspace/</workspace>
	<command>
		<executable>/app/SQUALE/OUTILS/JAVA/jdk1.5.0_09/bin/java</executable>
		<options>
			<option>-jar [squale_eclipse_home]/startup.jar</option>
			<option>-data [workspace]</option>
			<option>-application com.airfrance.squale.builder.eclipse32.workspaceId1</option>
			<option>-dialect [dialect]</option>
			<option>-sunLibs [sun_libs]</option>
			<option>-projects [projects_list]</option>
			<option>-vars [var_libs]</option>
			<option>-userLibs [user_libs]</option>
			<option>-excluded [excluded_patterns]</option>
		</options>
	</command>
	<squaleEclipseHome>/app/SQUALE/OUTILS/ECLIPSE/SQUALE_ECLIPSE_PLUGINS</squaleEclipseHome>
	<!-- ENV-ECLIPSE-HOME -->
	<eclipseHome>/app/SQUALE/dev/data/jcompiling/eclipse</eclipseHome>
	<!-- ENV-ECLIPSE-RIGHT_SCRIPT -->
	<rightScript>/app/SQUALE/dev/bin/java/resources/change_eclipse_classpath_rights.sh</rightScript>
	<!-- ENV-ECLIPSE-COPY-SCRIPT -->
	<copyScript>/app/SQUALE/dev/bin/java/resources/copy.sh</copyScript>
</configuration>
