=== jqk6/squale/Squale/squalix/src/main/resources/config/rsm-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configuration
	(general,profiles)
	
>
<!ELEMENT general
	(workspace,reportpath,reportmethodspath,reportclassespath,inputfile,auxfile,execcommand)
>

<!-- configuration de la commande d'exécution -->
<!ELEMENT execcommand (#PCDATA) >

<!-- Workspace réservé à McCabe -->
<!ELEMENT workspace
	(#PCDATA)
>
<!-- Chemin absolu du fichier contenant le rapport -->
<!ELEMENT reportpath
	(#PCDATA)
>

<!-- Chemin absolu du fichier contenant le rapport -->
<!ELEMENT reportmethodspath
	(#PCDATA)
>

<!-- Chemin absolu du fichier contenant le rapport -->
<!ELEMENT reportclassespath
	(#PCDATA)
>

<!-- Chemin du fichier liste passé en paramètre -->
<!ELEMENT inputfile
	(#PCDATA)
>

<!-- Chemin du fichier auxilliaire servant au préprocessing -->
<!ELEMENT auxfile
	(#PCDATA)
>

<!-- Liste des profils d'analyse -->
<!ELEMENT profiles
	(profile+)
>

<!ELEMENT profile
	(extensions,entetes,parameters)
>
<!ATTLIST profile
name CDATA #REQUIRED
>

<!--  Liste des extensions associées au profil séparées par une virgule  -->
<!ELEMENT extensions
	(#PCDATA)
>

<!-- Liste des entetes associées au profil séparées par une virgule -->
<!ELEMENT entetes
	(#PCDATA)
>

<!-- Liste des arguments de parsing des sources -->
<!ELEMENT parameters
	(parameter+)
>
<!ELEMENT parameter
	(#PCDATA)
>

=== jqk6/squale/Squale/squalix/src/assembly/resources/config/rsm-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- <!DOCTYPE configuration SYSTEM "rsm-config.dtd"> -->
<configuration>
	<general>
		<!-- ENV-RSM-WORKSPACE -->
		<workspace>/app/SQUALE/squalix/workspace</workspace>
		<!-- ENV-RSM-RPT -->
		<reportpath>/app/SQUALE/squalix/workspace/rapports_RSM.csv</reportpath>
		<!-- ENV-RSM-RPT-METHODS -->
		<reportmethodspath>/app/SQUALE/squalix/workspace/rapports_Methods_RSM.csv</reportmethodspath>
		<!-- ENV-RSM-RPT-CLASSES -->
		<reportclassespath>/app/SQUALE/squalix/workspace/rapports_Class_RSM.csv</reportclassespath>
		<!-- ENV-RSM-INPUT -->
		<inputfile>/app/SQUALE/squalix/workspace/input.txt</inputfile>
		<!-- ENV-RSM-AUX -->
		<auxfile>/app/SQUALE/squalix/workspace/aux.csv</auxfile>
		<!-- ENV-RSM-EXEC -->
		<execcommand>/app/SQUALE/OUTILS/RSM/7.0/rsm</execcommand>
	</general>
	<profiles>
		 <profile name="java">
	      	<extensions>.java</extensions>
	      	<entetes></entetes>
	      	<parameters>
	      		<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
		 <profile name="java compiled">
	      	<extensions>.java</extensions>
	      	<entetes></entetes>
	      	<parameters>
	      		<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
	     <profile name="j2ee">
	      	<extensions>.java</extensions>
	      	<entetes></entetes>
	      	<parameters>
	      		<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
	     <profile name="j2ee compiled">
	      	<extensions>.java</extensions>
	      	<entetes></entetes>
	      	<parameters>
	      		<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
	     <profile name="cpp">
	     	<extensions>.c,.cc,.cxx,.cpp,.C</extensions>
	      	<entetes>.h,.hh,.hxx,.hpp</entetes>
	     	<parameters>
		      	<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
    </profiles>
</configuration>

=== jqk6/squale/Squale/squalix/src/test/java/config/rsm-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- <!DOCTYPE configuration SYSTEM "rsm-config.dtd"> -->
<configuration>
	<general>
		<workspace>D:\temp\rsm</workspace>
		<reportpath>D:\temp\rsm\rapport.csv</reportpath>
		<reportmethodspath>D:\temp\rsm\rapports_Methods_RSM.csv</reportmethodspath>
		<reportclassespath>D:\temp\rsm\rapports_Class_RSM.csv</reportclassespath>
		<auxfile>D:\temp\rsm\rapports_aux_RSM.csv</auxfile>
		<inputfile>D:\temp\rsm\input.txt</inputfile>
		<execcommand>D:\temp\rsm\rsm</execcommand>
	</general>
	<profiles>
		 <profile name="java">
	      	<extensions>.java</extensions>
	      	<entetes></entetes>
	      	<parameters>
	      		<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
	     <profile name="j2ee">
	      	<extensions>.java</extensions>
	      	<entetes></entetes>
	      	<parameters>
	      		<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
	     <profile name="cpp">
	     	<extensions>.c,.cc,.cxx,.cpp,.C</extensions>
	      	<entetes>.h,.hh,.hxx,.hpp</entetes>
	     	<parameters>
		      	<!-- CSV output mode -->
	        	<parameter>-A</parameter>
	        	<!-- les options pour récupérer le type de données voulues -->
	        	<parameter>-Tf</parameter>
	        	<!-- Pour avoir les métriques orientés objets -->
	        	<parameter>-To</parameter>
	        	<!-- Pour prendre une liste de fichiers en paramètres -->
	        	<parameter>-F</parameter>
	        	<!-- Fichier de sortie, sinon s'affiche à l'écran -->
	        	<parameter>-O</parameter>
	      	</parameters>
	     </profile>
    </profiles>
</configuration>
